env:
  browser: true
  es6: true
extends:
  - airbnb-base
  - plugin:jest/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  # Required to make lambda callbackWaitsForEmptyEventLoop work
  no-param-reassign: off,

  jest/no-disabled-tests: warn,
  jest/no-focused-tests: error,
  jest/no-identical-title: error,
  jest/prefer-to-have-length: warn,
  jest/valid-expect: error,

}
plugins:
  - jest
